import * as v from 'valibot';

export const TriviaQuestion = v.object({
	q: v.pipe(v.string(), v.trim(), v.minLength(3), v.maxLength(200)),
	choices: v.pipe(
		v.array(v.pipe(v.string(), v.trim(), v.minLength(1), v.maxLength(80))),
		v.minLength(2),
		v.maxLength(4)
	),
	/** Index into `choices` of the right answer. */
	answer: v.pipe(v.number(), v.integer(), v.minValue(0)),
	/** Shown after the reveal. */
	fact: v.optional(v.pipe(v.string(), v.trim(), v.maxLength(240)))
});

const packFields = {
	title: v.pipe(v.string(), v.trim(), v.minLength(2), v.maxLength(60)),
	description: v.pipe(v.string(), v.trim(), v.maxLength(160)),
	emoji: v.optional(v.pipe(v.string(), v.maxLength(16))),
	language: v.optional(v.string(), 'en'),
	questions: v.pipe(
		v.array(TriviaQuestion),
		v.minLength(3, 'Add at least 3 questions'),
		v.maxLength(100, 'Packs can have at most 100 questions')
	)
};

const ANSWERS_IN_RANGE = 'Every answer must point at one of its choices';
const answersInRange = (questions: { answer: number; choices: string[] }[]) =>
	questions.every((q) => q.answer < q.choices.length);

/** A pack as written by a host or generated by AI, before it has an id. */
export const TriviaPackDraft = v.pipe(
	v.object(packFields),
	v.check((p) => answersInRange(p.questions), ANSWERS_IN_RANGE)
);

export const TriviaPack = v.pipe(
	v.object({ id: v.pipe(v.string(), v.regex(/^[a-zA-Z0-9-]{2,40}$/)), ...packFields }),
	v.check((p) => answersInRange(p.questions), ANSWERS_IN_RANGE)
);

export type TriviaQuestion = v.InferOutput<typeof TriviaQuestion>;
export type TriviaPack = v.InferOutput<typeof TriviaPack>;
export type TriviaPackDraft = v.InferOutput<typeof TriviaPackDraft>;
